import Link from "next/link";
import { CalendarDays, HeartHandshake, Hospital } from "lucide-react";
import { EmptyState, StatusBadge } from "@/components/portal-widgets";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

export function ReferralsPage({ mode, referrals, followUps }: { mode: "staff" | "admin"; referrals: any[]; followUps: any[] }) {
  const rows = [
    ...referrals.map((item) => ({ ...item, type: "Referral", date: item.created_at, participant: Array.isArray(item.participants) ? item.participants[0] : item.participants })),
    ...followUps.map((item) => ({ ...item, type: "Follow-up", date: item.suggested_date || item.created_at, participant: Array.isArray(item.participants) ? item.participants[0] : item.participants })),
  ].sort((a,b)=>String(a.date).localeCompare(String(b.date)));
  return <Card className="overflow-hidden shadow-sm"><div className="flex flex-col gap-3 border-b border-[#e8e3db] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-[#242930]">Referrals and follow-ups</h2><p className="mt-1 text-xs leading-5 text-[#7a818a]">Operational queue generated from screening records. Core data is never re-entered here.</p></div><div className="flex gap-2"><Badge variant="destructive">{referrals.length} referrals</Badge><Badge variant="warning">{followUps.length} follow-ups</Badge></div></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left"><thead><tr className="bg-[#faf9f6] text-[10px] font-black uppercase tracking-[.1em] text-[#7b818a]"><th className="px-5 py-3">Participant</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Facility / date</th><th className="px-5 py-3">Contact permission</th><th className="px-5 py-3">Status</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-[#ece8e0]">{rows.map((item:any)=><tr key={`${item.type}-${item.id}`} className="hover:bg-[#faf9f6]"><td className="px-5 py-4"><p className="text-sm font-semibold text-[#272c33]">{item.participant?.full_name}</p><p className="mt-1 font-mono text-xs text-[#225f9d]">{item.participant?.registration_number}</p></td><td className="px-5 py-4"><span className="inline-flex items-center gap-2 text-sm font-semibold">{item.type==="Referral"?<Hospital className="size-4 text-[var(--bua-red)]"/>:<CalendarDays className="size-4 text-[#8a5a00]"/>}{item.type}</span></td><td className="px-5 py-4 text-sm text-[#58606a]">{item.type==="Referral" ? ((Array.isArray(item.referral_hospitals)?item.referral_hospitals[0]:item.referral_hospitals)?.name || "Facility not selected") : (item.suggested_date || "Date not selected")}</td><td className="px-5 py-4 text-sm text-[#58606a]">{item.participant?.medical_contact_permission ? "Yes" : "No"}</td><td className="px-5 py-4"><StatusBadge status={item.status}/></td><td className="px-5 py-4"><Link href={`/${mode}/participants/${item.participant?.id}`} className="text-xs font-bold text-[var(--bua-red)] hover:underline">Open profile</Link></td></tr>)}</tbody></table></div> : <EmptyState icon={HeartHandshake} title="No open referrals or follow-ups" description="Cases will appear here automatically when a completed screening requires further action."/>}</Card>;
}
