"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AnimatePresence, motion } from "motion/react";
import { Activity, ArrowLeft, ArrowRight, CalendarDays, Check, ClipboardCheck, Hospital, LoaderCircle, Save, ShieldCheck, Stethoscope } from "lucide-react";
import { toast } from "sonner";
import { PortalShell } from "@/components/portal-shell";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

const steps = [
  { title: "Measurements", icon: Activity, description: "Package delivered and objective screening measurements." },
  { title: "Clinical review", icon: Stethoscope, description: "Doctor consultation and clinical decisions." },
  { title: "Referral and follow-up", icon: Hospital, description: "Complete only the sections triggered by the review." },
  { title: "Review and complete", icon: ClipboardCheck, description: "Confirm every value before formal completion." },
];

type Props = { mode: "staff" | "admin"; profile: { full_name: string; staff_id: string; role: string }; participant: any; hospitals: any[] };

function Field({ label, required, hint, children }: { label: string; required?: boolean; hint?: string; children: React.ReactNode }) { return <div className="space-y-2.5"><div className="flex items-baseline justify-between gap-3"><Label className="text-sm font-semibold text-[#2b3038]">{label}{required && <span className="ml-1 text-[var(--bua-red)]">*</span>}</Label>{hint && <span className="text-xs text-[#7c828b]">{hint}</span>}</div>{children}</div>; }
function YesNo({ value, onChange, name }: { value: string; onChange: (value: string) => void; name: string }) { return <RadioGroup value={value} onValueChange={onChange} className="grid grid-cols-2 gap-2">{["Yes","No"].map((option) => <Label key={option} htmlFor={`${name}-${option}`} className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#ded9cf] bg-white p-3.5 font-semibold has-[[data-state=checked]]:border-[var(--zendale-blue)] has-[[data-state=checked]]:bg-[#f4f7fb] has-[[data-state=checked]]:text-[var(--zendale-blue)]"><RadioGroupItem id={`${name}-${option}`} value={option}/>{option}</Label>)}</RadioGroup>; }
function Summary({ label, value, internal = false }: { label: string; value: React.ReactNode; internal?: boolean }) { return <div className="grid gap-1 border-b border-[#ece8e0] py-3.5 last:border-0 sm:grid-cols-[180px_1fr]"><p className="text-[10px] font-black uppercase tracking-[.1em] text-[#858b94]">{label}{internal && <span className="ml-2 rounded-full bg-[#efede8] px-2 py-0.5 text-[9px]">Internal</span>}</p><div className="text-sm font-semibold leading-6 text-[#343a43]">{value || "—"}</div></div>; }

export function ScreeningForm({ mode, profile, participant, hospitals }: Props) {
  const router = useRouter();
  const existing = Array.isArray(participant.screenings) ? participant.screenings[0] : participant.screenings;
  const referral = existing && Array.isArray(existing.referrals) ? existing.referrals[0] : existing?.referrals;
  const followUp = existing && Array.isArray(existing.follow_ups) ? existing.follow_ups[0] : existing?.follow_ups;
  const [step, setStep] = useState(0);
  const [saving, setSaving] = useState(false);
  const [data, setData] = useState({
    screeningPackage: existing?.screening_package || participant.requested_service || "Free Wellness Screening",
    systolic: existing?.systolic?.toString() || "", diastolic: existing?.diastolic?.toString() || "", randomBloodSugar: existing?.random_blood_sugar?.toString() || "",
    screeningDate: existing?.screening_date || new Date().toISOString().slice(0,10), doctorSeen: existing?.doctor_seen === true ? "Yes" : existing?.doctor_seen === false ? "No" : "",
    clinicalNote: existing?.clinical_note || "", referralRequired: existing?.referral_required ? "Yes" : "No", followUpRequired: existing?.follow_up_required ? "Yes" : "No",
    referralHospitalId: referral?.referral_hospital_id || "", referralReason: referral?.reason || "", referralInstruction: referral?.participant_instruction || "", urgency: referral?.urgency || "Routine", participantInformed: referral?.participant_informed ? "Yes" : "No",
    followUpReason: followUp?.reason || "", followUpDate: followUp?.suggested_date || "", followUpInstruction: followUp?.participant_instruction || "",
  });
  const update = (key: keyof typeof data, value: string) => setData((current) => ({ ...current, [key]: value }));
  const error = useMemo(() => {
    if (step === 0 && (!data.screeningPackage || !data.systolic || !data.diastolic || !data.randomBloodSugar || !data.screeningDate)) return "Complete every required measurement field.";
    if (step === 1 && (!data.doctorSeen || !data.referralRequired || !data.followUpRequired)) return "Complete every clinical decision field.";
    if (step === 2 && data.referralRequired === "Yes" && (!data.referralHospitalId || !data.referralReason || !data.referralInstruction || !data.urgency || !data.participantInformed)) return "Complete every required referral field.";
    if (step === 2 && data.followUpRequired === "Yes" && (!data.followUpReason || !data.followUpInstruction)) return "Complete every required follow-up field.";
    return "";
  }, [data, step]);
  const submit = async (action: "save" | "complete" | "update") => {
    if (action !== "save" && error) return toast.error(error);
    setSaving(true);
    try {
      const response = await fetch("/api/staff/screenings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ participantId: participant.id, screeningPackage: data.screeningPackage, systolic: data.systolic, diastolic: data.diastolic, randomBloodSugar: data.randomBloodSugar, screeningDate: data.screeningDate, doctorSeen: data.doctorSeen === "Yes", clinicalNote: data.clinicalNote, referralRequired: data.referralRequired === "Yes", followUpRequired: data.followUpRequired === "Yes", referralHospitalId: data.referralHospitalId || null, referralReason: data.referralReason, referralInstruction: data.referralInstruction, urgency: data.referralRequired === "Yes" ? data.urgency : null, participantInformed: data.referralRequired === "Yes" ? data.participantInformed === "Yes" : null, followUpReason: data.followUpReason, followUpDate: data.followUpDate || null, followUpInstruction: data.followUpInstruction, action }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error || "The screening could not be saved.");
      toast.success(action === "save" ? "Screening draft saved." : action === "complete" ? "Screening completed." : "Screening updated.");
      router.push(`/${mode}/participants/${participant.id}`); router.refresh();
    } catch (err) { toast.error(err instanceof Error ? err.message : "The screening could not be saved."); setSaving(false); }
  };
  const content = [
    <div key="measure" className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Registration number"><Input value={participant.registration_number} disabled/></Field></div><div className="sm:col-span-2"><Field label="Screening package delivered" required><Select value={data.screeningPackage} onValueChange={(v)=>update("screeningPackage",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Free Wellness Screening","Standard Package","Comprehensive Package","Doctor Consultation Only"].map((item)=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Blood pressure" required hint="mmHg"><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><Input type="number" value={data.systolic} onChange={(e)=>update("systolic",e.target.value)} placeholder="Systolic"/><span className="font-bold text-[#858b94]">/</span><Input type="number" value={data.diastolic} onChange={(e)=>update("diastolic",e.target.value)} placeholder="Diastolic"/></div></Field><Field label="Random blood sugar" required hint="mmol/L"><Input type="number" step="0.1" value={data.randomBloodSugar} onChange={(e)=>update("randomBloodSugar",e.target.value)}/></Field><Field label="Screening date" required><Input type="date" value={data.screeningDate} onChange={(e)=>update("screeningDate",e.target.value)}/></Field><Field label="Staff identity"><Input value={`${profile.full_name} · ${profile.staff_id}`} disabled/></Field><div className="sm:col-span-2"><Alert><ShieldCheck className="absolute left-4 top-4 size-5 text-[var(--zendale-blue)]"/><AlertTitle className="pl-7">Validation supports accurate entry</AlertTitle><AlertDescription className="pl-7">Range checks can detect likely typing mistakes. The system does not make a diagnosis.</AlertDescription></Alert></div></div>,
    <div key="clinical" className="space-y-6"><Card className="p-5 shadow-sm"><Field label="Was the participant seen by a doctor?" required><YesNo name="doctor" value={data.doctorSeen} onChange={(v)=>update("doctorSeen",v)}/></Field></Card><Field label="Clinical observation / internal note" hint="Never shown in participant lookup"><Textarea value={data.clinicalNote} onChange={(e)=>update("clinicalNote",e.target.value)} className="min-h-36" placeholder="Record concise and factual internal observations"/></Field><div className="grid gap-5 sm:grid-cols-2"><Card className="p-5 shadow-sm"><Field label="Referral required?" required><YesNo name="referral" value={data.referralRequired} onChange={(v)=>update("referralRequired",v)}/></Field></Card><Card className="p-5 shadow-sm"><Field label="Follow-up required?" required><YesNo name="followup" value={data.followUpRequired} onChange={(v)=>update("followUpRequired",v)}/></Field></Card></div></div>,
    <div key="actions" className="space-y-6">{data.referralRequired === "Yes" ? <Card className="space-y-5 border-[#ead9a0] bg-[#fffdf7] p-5"><div className="flex items-center gap-3"><Hospital className="size-5 text-[#8a5a00]"/><h3 className="font-bold">Referral details</h3></div><Field label="Referral hospital" required><Select value={data.referralHospitalId} onValueChange={(v)=>update("referralHospitalId",v)}><SelectTrigger><SelectValue placeholder="Select an active hospital"/></SelectTrigger><SelectContent>{hospitals.map((h)=><SelectItem key={h.id} value={h.id}>{h.name}{h.department_specialty ? ` · ${h.department_specialty}` : ""}</SelectItem>)}</SelectContent></Select></Field><Field label="Referral reason" required><Textarea value={data.referralReason} onChange={(e)=>update("referralReason",e.target.value)}/></Field><Field label="Participant instruction" required><Textarea value={data.referralInstruction} onChange={(e)=>update("referralInstruction",e.target.value)}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Urgency" required><Select value={data.urgency} onValueChange={(v)=>update("urgency",v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Routine","Within 7 days","Urgent"].map((item)=><SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><Field label="Participant informed?" required><YesNo name="informed" value={data.participantInformed} onChange={(v)=>update("participantInformed",v)}/></Field></div></Card> : <Card className="border-dashed p-5 text-sm text-[#717882]">Referral fields are hidden because Referral Required is No.</Card>}{data.followUpRequired === "Yes" ? <Card className="space-y-5 p-5"><div className="flex items-center gap-3"><CalendarDays className="size-5 text-[#157347]"/><h3 className="font-bold">Follow-up details</h3></div><Field label="Follow-up reason" required><Textarea value={data.followUpReason} onChange={(e)=>update("followUpReason",e.target.value)}/></Field><Field label="Suggested follow-up date"><Input type="date" value={data.followUpDate} onChange={(e)=>update("followUpDate",e.target.value)}/></Field><Field label="Participant instruction" required><Textarea value={data.followUpInstruction} onChange={(e)=>update("followUpInstruction",e.target.value)}/></Field></Card> : <Card className="border-dashed p-5 text-sm text-[#717882]">Follow-up fields are hidden because Follow-up Required is No.</Card>}</div>,
    <div key="review" className="space-y-5"><Card className="px-5 shadow-sm"><Summary label="Participant" value={`${participant.full_name} · ${participant.registration_number}`}/><Summary label="Package" value={data.screeningPackage}/><Summary label="Blood pressure" value={`${data.systolic || "—"} / ${data.diastolic || "—"} mmHg`}/><Summary label="Random blood sugar" value={data.randomBloodSugar ? `${data.randomBloodSugar} mmol/L` : "—"}/><Summary label="Doctor seen" value={data.doctorSeen}/><Summary label="Clinical note" value={data.clinicalNote} internal/><Summary label="Referral" value={data.referralRequired === "Yes" ? `${hospitals.find((h)=>h.id===data.referralHospitalId)?.name || "Hospital not selected"} · ${data.urgency}` : "Not required"}/><Summary label="Follow-up" value={data.followUpRequired === "Yes" ? `${data.followUpDate || "Date not set"} · ${data.followUpInstruction}` : "Not required"}/></Card><Alert className="border-[#f0cbd1] bg-[#fff7f8] text-[#6f2430]"><AlertTitle>Formal completion locks ordinary editing</AlertTitle><AlertDescription>After completion, the record opens read-only. An authorised correction changes the status to Updated and preserves the original completion metadata.</AlertDescription></Alert></div>,
  ];
  const action = existing?.status === "completed" || existing?.status === "updated" ? "update" : "complete";
  return <PortalShell mode={mode} profile={profile} title={existing ? "Screening record" : "Start screening"} description={`${participant.full_name} · ${participant.registration_number}`} action={<Button asChild variant="outline"><Link href={`/${mode}/participants/${participant.id}`}><ArrowLeft/> Participant profile</Link></Button>}><Card className="overflow-hidden shadow-sm"><div className="border-b border-[#e8e3db] bg-[#faf9f6] p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[var(--bua-red)]">Step {step+1} of 4</p><p className="mt-1 text-sm font-semibold text-[#555d68]">{steps[step].title}</p></div><span className="text-sm font-black">{Math.round(((step+1)/4)*100)}%</span></div><Progress value={((step+1)/4)*100}/><div className="no-scrollbar mt-5 flex gap-2 overflow-x-auto">{steps.map((item,index)=>{ const Icon=item.icon; return <button key={item.title} type="button" onClick={()=>index<=step&&setStep(index)} disabled={index>step} className={cn("flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs font-semibold", index===step && "bg-[#17243a] text-white", index<step && "bg-[#eaf1fb] text-[#225f9d]", index>step && "text-[#a0a4aa]")}><span className="grid size-6 place-items-center rounded-lg bg-white/10">{index<step ? <Check className="size-3.5"/> : <Icon className="size-3.5"/>}</span>{item.title}</button>;})}</div></div><div className="p-5 sm:p-8"><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{content[step]}</motion.div></AnimatePresence>{error && <p className="mt-5 rounded-xl bg-[#fff1f3] px-4 py-3 text-sm font-semibold text-[#9d1729]">{error}</p>}<div className="mt-8 flex flex-col-reverse justify-between gap-3 border-t border-[#ece8df] pt-6 sm:flex-row"><div className="flex gap-2"><Button variant="outline" onClick={()=>setStep(Math.max(0,step-1))} disabled={step===0}><ArrowLeft/> Back</Button><Button variant="secondary" onClick={()=>submit("save")} disabled={saving}><Save/> Save & exit</Button></div>{step<3 ? <Button onClick={()=>{if(error)return toast.error(error);setStep(step+1);}}>Continue <ArrowRight/></Button> : <Button onClick={()=>submit(action)} disabled={saving}>{saving ? <><LoaderCircle className="animate-spin"/> Saving…</> : action === "update" ? "Save authorised update" : "Complete screening"}</Button>}</div></div></Card></PortalShell>;
}
