import ExcelJS from "exceljs";
import { participants, hospitals, staffMembers } from "@/lib/mock-data";

function styleSheet(sheet: ExcelJS.Worksheet) {
  sheet.views = [{ state: "frozen", ySplit: 1 }];
  sheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: 1, column: sheet.columnCount } };
  sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  sheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF0B4654" } };
  sheet.getRow(1).alignment = { vertical: "middle" };
  sheet.getRow(1).height = 24;
  sheet.columns.forEach((column) => { column.width = Math.max(16, Math.min(34, column.header?.toString().length ? column.header.toString().length + 6 : 18)); });
}

export async function GET() {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "BUA Health Outreach";
  workbook.created = new Date();
  workbook.properties.date1904 = false;

  const participantSheet = workbook.addWorksheet("Participants");
  participantSheet.columns = [
    { header: "Registration Number", key: "reg" }, { header: "Participant", key: "name" }, { header: "Phone", key: "phone" }, { header: "Masked Email", key: "email" }, { header: "Department", key: "department" }, { header: "Requested Service", key: "service" }, { header: "Screening Status", key: "status" }, { header: "Registered At", key: "registeredAt", style: { numFmt: "yyyy-mm-dd hh:mm" } },
  ];
  participants.forEach((participant, index) => participantSheet.addRow({ ...participant, registeredAt: new Date(2026, 6, 17, 9, 20 + index * 6) }));
  styleSheet(participantSheet);

  const screeningSheet = workbook.addWorksheet("Screenings");
  screeningSheet.columns = [
    { header: "Screening ID", key: "id" }, { header: "Registration Number", key: "reg" }, { header: "Package Delivered", key: "package" }, { header: "Blood Pressure", key: "bp" }, { header: "Random Blood Sugar", key: "rbs" }, { header: "Status", key: "status" }, { header: "Completed By", key: "completedBy" }, { header: "Completed At", key: "completedAt", style: { numFmt: "yyyy-mm-dd hh:mm" } },
  ];
  participants.filter((item) => item.status !== "Not Started").forEach((participant, index) => screeningSheet.addRow({ id: `SCR-2026-${1047-index}`, reg: participant.reg, package: participant.service, bp: index % 2 ? "118/76" : "124/81", rbs: index % 2 ? 5.2 : 5.8, status: participant.status, completedBy: "BUA-STF-001", completedAt: new Date(2026, 6, 17, 10, 10 + index * 8) }));
  styleSheet(screeningSheet);

  const referralSheet = workbook.addWorksheet("Referrals");
  referralSheet.columns = [{ header: "Registration Number", key: "reg" }, { header: "Participant", key: "name" }, { header: "Hospital", key: "hospital" }, { header: "Urgency", key: "urgency" }, { header: "Participant Informed", key: "informed" }, { header: "Status", key: "status" }];
  participants.filter((item) => item.referral).forEach((participant) => referralSheet.addRow({ reg: participant.reg, name: participant.name, hospital: hospitals[0].name, urgency: "Within 7 days", informed: "Yes", status: "Scheduled" }));
  styleSheet(referralSheet);

  const followSheet = workbook.addWorksheet("Follow-ups");
  followSheet.columns = [{ header: "Registration Number", key: "reg" }, { header: "Participant", key: "name" }, { header: "Suggested Date", key: "date", style: { numFmt: "yyyy-mm-dd" } }, { header: "Contact Permission", key: "permission" }, { header: "Status", key: "status" }];
  participants.filter((item) => item.followUp).forEach((participant, index) => followSheet.addRow({ reg: participant.reg, name: participant.name, date: new Date(2026, 6, 24 + index), permission: index === 1 ? "No" : "Yes", status: "Pending" }));
  styleSheet(followSheet);

  const completeSheet = workbook.addWorksheet("Complete Records");
  completeSheet.columns = participantSheet.columns.map((column) => ({ header: column.header?.toString() || "", key: column.key?.toString() || "" }));
  participants.forEach((participant, index) => completeSheet.addRow({ ...participant, registeredAt: new Date(2026, 6, 17, 9, 20 + index * 6) }));
  styleSheet(completeSheet);

  const staffSheet = workbook.addWorksheet("Staff Activity");
  staffSheet.columns = [{ header: "Staff ID", key: "id" }, { header: "Staff Name", key: "name" }, { header: "Role", key: "role" }, { header: "Status", key: "status" }, { header: "Last Activity", key: "lastSeen" }];
  staffMembers.forEach((staff) => staffSheet.addRow(staff));
  styleSheet(staffSheet);

  const metadata = workbook.addWorksheet("Export Info");
  metadata.addRows([["Generated At", new Date()], ["Generated By", "BUA-STF-001"], ["Filters", "Registration date: 2026-07-01 to 2026-07-17; all statuses"], ["Security", "Private lookup-code plaintext and passwords excluded"]]);
  metadata.getColumn(1).font = { bold: true }; metadata.getColumn(1).width = 22; metadata.getColumn(2).width = 70;

  const buffer = await workbook.xlsx.writeBuffer();
  const timestamp = new Date().toISOString().replace(/[:T]/g, "-").slice(0, 16);
  return new Response(buffer as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": `attachment; filename="BUA_Health_Outreach_Export_${timestamp}.xlsx"`,
      "Cache-Control": "no-store",
    },
  });
}
