"use client";

import { FormEvent, useState } from "react";
import { Building2, LoaderCircle, Plus, ToggleLeft, ToggleRight } from "lucide-react";
import { toast } from "sonner";
import { EmptyState, StatusBadge } from "@/components/portal-widgets";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export function HospitalsAdmin({ initial }: { initial: any[] }) {
  const [items, setItems] = useState(initial); const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ name: "", address: "", phone: "", departmentSpecialty: "", participantInstruction: "" });
  const update=(key:keyof typeof form,value:string)=>setForm((current)=>({...current,[key]:value}));
  const create=async(event:FormEvent)=>{event.preventDefault();setLoading(true);try{const response=await fetch("/api/admin/hospitals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Hospital could not be created.");setItems((current)=>[...current,result].sort((a,b)=>a.name.localeCompare(b.name)));setForm({name:"",address:"",phone:"",departmentSpecialty:"",participantInstruction:""});toast.success("Referral hospital added.");}catch(error){toast.error(error instanceof Error?error.message:"Hospital could not be created.");}finally{setLoading(false);}};
  const toggle=async(item:any)=>{try{const response=await fetch("/api/admin/hospitals",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,active:!item.active})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Update failed.");setItems((current)=>current.map((row)=>row.id===item.id?{...row,active:!row.active}:row));toast.success(`Hospital ${item.active?"deactivated":"activated"}.`);}catch(error){toast.error(error instanceof Error?error.message:"Update failed.");}};
  return <div className="grid gap-6 xl:grid-cols-[.72fr_1.28fr]"><Card className="h-fit p-6 shadow-sm"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#eaf1fb] text-[var(--zendale-blue)]"><Plus className="size-4"/></div><div><h2 className="font-bold">Add referral hospital</h2><p className="mt-1 text-xs text-[#7b818a]">Only active hospitals appear in new screening referrals.</p></div></div><form onSubmit={create} className="mt-6 space-y-4"><div className="space-y-2"><Label>Hospital name *</Label><Input value={form.name} onChange={(e)=>update("name",e.target.value)} required/></div><div className="space-y-2"><Label>Department / specialty</Label><Input value={form.departmentSpecialty} onChange={(e)=>update("departmentSpecialty",e.target.value)}/></div><div className="space-y-2"><Label>Address</Label><Input value={form.address} onChange={(e)=>update("address",e.target.value)}/></div><div className="space-y-2"><Label>Phone number</Label><Input value={form.phone} onChange={(e)=>update("phone",e.target.value)}/></div><div className="space-y-2"><Label>Default participant instruction</Label><Textarea value={form.participantInstruction} onChange={(e)=>update("participantInstruction",e.target.value)}/></div><Button type="submit" className="w-full" disabled={loading}>{loading?<><LoaderCircle className="animate-spin"/> Adding…</>:"Add hospital"}</Button></form></Card><Card className="overflow-hidden shadow-sm"><div className="border-b border-[#e8e3db] p-5"><h2 className="font-bold">Hospital directory</h2><p className="mt-1 text-xs text-[#7b818a]">Inactive hospitals remain in historical records but disappear from new referral dropdowns.</p></div>{items.length?<div className="divide-y divide-[#ece8e0]">{items.map((item)=><div key={item.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-[#efede8] text-[#59606a]"><Building2 className="size-4.5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#272c33]">{item.name}</p><StatusBadge status={item.active?"active":"inactive"}/></div><p className="mt-1 text-xs leading-5 text-[#7b818a]">{item.department_specialty||"No specialty set"}{item.phone?` · ${item.phone}`:""}</p></div><Button variant="outline" size="sm" onClick={()=>toggle(item)}>{item.active?<ToggleRight/>:<ToggleLeft/>}{item.active?"Deactivate":"Activate"}</Button></div>)}</div>:<EmptyState icon={Building2} title="No referral hospitals" description="Add an approved facility to make it available in screening referrals."/>}</Card></div>;
}
