import Link from "next/link";
import { ClipboardCheck } from "lucide-react";
import { requirePortalProfile } from "@/lib/auth";
import { getScreenings } from "@/lib/data/portal";
import { PortalShell } from "@/components/portal-shell";
import { EmptyState, StatusBadge } from "@/components/portal-widgets";
import { Card } from "@/components/ui/card";
export const dynamic="force-dynamic";
export default async function Page(){const profile=await requirePortalProfile("admin");const screenings=await getScreenings();return <PortalShell mode="admin" profile={profile} title="Screening records" description="Read-only oversight of in-progress, completed and updated screening records."><Card className="overflow-hidden shadow-sm">{screenings.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="bg-[#faf9f6] text-[10px] font-black uppercase tracking-[.1em] text-[#7b818a]"><th className="px-5 py-3">Registration</th><th className="px-5 py-3">Participant</th><th className="px-5 py-3">Package</th><th className="px-5 py-3">Measurements</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Last activity</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y divide-[#ece8e0]">{screenings.map((item:any)=>{const participant=Array.isArray(item.participants)?item.participants[0]:item.participants;return <tr key={item.id} className="hover:bg-[#faf9f6]"><td className="px-5 py-4 font-mono text-sm font-bold text-[#225f9d]">{participant?.registration_number}</td><td className="px-5 py-4"><p className="text-sm font-semibold">{participant?.full_name}</p><p className="mt-1 text-xs text-[#7b818a]">{participant?.department}</p></td><td className="px-5 py-4 text-sm text-[#58606a]">{item.screening_package}</td><td className="px-5 py-4 text-sm text-[#58606a]">{item.systolic&&item.diastolic?`${item.systolic}/${item.diastolic} mmHg`:"—"}{item.random_blood_sugar?` · ${item.random_blood_sugar} mmol/L`:""}</td><td className="px-5 py-4"><StatusBadge status={item.status}/></td><td className="px-5 py-4 text-xs text-[#7b818a]">{new Date(item.updated_at).toLocaleString("en-GB")}</td><td className="px-5 py-4"><Link href={`/admin/screenings/${participant?.id}`} className="text-xs font-bold text-[var(--bua-red)] hover:underline">Open</Link></td></tr>})}</tbody></table></div>:<EmptyState icon={ClipboardCheck} title="No screening records" description="Records will appear after authorised medical staff save the first screening."/>}</Card></PortalShell>;}
